# roles/apache2/tasks/main.yml
---
- name: Install Apache2
  apt:
    name: apache2
    state: present
    update_cache: yes
  become: true

- name: Ensure Apache2 is running and enabled
  service:
    name: apache2
    state: started
    enabled: true
  become: true

- name: Copy Apache VirtualHost configuration
  template:
    src: apache_vhost.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  become: true

- name: Restart Apache2 to apply configuration
  service:
    name: apache2
    state: restarted
  become: true
  notify:
    - restart apache
