server_name: "mywebserver.com"
# server_aliases: ["www.mywebserver.com", "mywebserver.net"]
server_aliases: ["www.mywebserver.com", "mywebserver.net"]
# document_root: "/var/www/html"
document_root: "/var/www/html"
# # ssl_cert_path: "/etc/ssl/certs/mywebserver.crt"
# ssl_cert_path: "/etc/ssl/certs/mywebserver.crt"
# # ssl_key_path: "/etc/ssl/private/mywebserver.key"
# ssl_key_path: "/etc/ssl/private/mywebserver.key"
# # ssl_chain_path: "/etc/ssl/certs/mywebserver-chain.crt"
# ssl_chain_path: "/etc/ssl/certs/mywebserver-chain.crt"
# # ssl_enabled: true
# ssl_enabled: true
# # ssl_protocols: "TLSv1.2 TLSv1.3"
# ssl_protocols: "TLSv1.2 TLSv1.3"
# # ssl_ciphers: "HIGH:!aNULL:!MD5"
# ssl_ciphers: "HIGH:!aNULL:!MD5"
# # ssl_prefer_server_ciphers: "on"
# ssl_prefer_server_ciphers: "on"
# # ssl_session_cache: "shared:SSL:10m"
# ssl_session_cache: "shared:SSL:10m"
# # ssl_session_timeout: "5m"
# ssl_session_timeout: "5m"
# # ssl_dhparam_path: "/etc/ssl/certs/dhparam.pem"
# ssl_dhparam_path: "/etc/ssl/certs/dhparam.pem"
# # ssl_stapling: "on"
# ssl_stapling: "on"
# # ssl_stapling_verify: "on"
# ssl_stapling_verify: "on"
# # ssl_stapling_file: "/var/run/ocsp-ssl-stapling"
# ssl_stapling_file: "/var/run/ocsp-ssl-stapling"
# # ssl_stapling_responder: "http://ocsp.example.com"
# ssl_stapling_responder: "http://ocsp.example.com"
# # ssl_stapling_ttl: "5m"
# ssl_stapling_ttl: "5m"
# # ssl_stapling_error: "on"
# ssl_stapling_error: "on"
# # ssl_stapling_error_ttl: "5m"
# ssl_stapling_error_ttl: "5m"
# # ssl_stapling_error_file: "/var/run/ocsp-ssl-stapling-error"
# ssl_stapling_error_file: "/var/run/ocsp-ssl-stapling-error"
# # ssl_stapling_error_responder: "http://ocsp-error.example.com"
# ssl_stapling_error_responder: "http://ocsp-error.example.com"
# # ssl_stapling_error_ttl: "5m"

