---

- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist
  become: true
  register: apt_update
  when: ansible_os_family == "Debian"
  tags: common

- name: Install common packages
  apt:
    name: "{{ item  }}"
    state: present
  loop: "{{ common_packages }}"
  become: true
  when: ansible_os_family == "Debian"
  tags: common